//! Stable UI identities. Labels come from the same catalog used by real widgets.
//! Recording is opt-in; the native viewer does not retain a documentation trace.
use crate::document::PolyhedronType;

// The browser has no guide recorder: select no-op hooks without per-widget
// context lookups, locks, or retained trace data. Native tracing stays opt-in.
#[cfg_attr(target_arch = "wasm32", path = "controls/no_trace.rs")]
#[cfg_attr(not(target_arch = "wasm32"), path = "controls/trace.rs")]
mod tracing;
pub use tracing::*;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub enum Control {
    ToolDock,
    TerminalPanelToggle,
    TerminalPanel,
    TerminalViewport,
    TerminalStatus,
    AnimationPanelToggle,
    ToolDockTabBar,
    ToolDockClose,
    AnimationTimeline,
    AnimationRuler,
    AnimationFit,
    SceneHierarchy,
    #[allow(dead_code)] // Retained catalog identity for scene inspection controls.
    ScenePicker,
    SceneClip,
    ScenePlay,
    SceneRest,
    SceneTime,
    SceneLoop,
    SceneSpeed,
    #[allow(dead_code)] // Retained catalog identity for scene inspection controls.
    SceneCamera,
    SceneExposure,
    SceneDetails,
    SceneDiagnostics,
    N3Menu,
    FileMenu,
    Open,
    Import,
    Frame,
    Projection,
    ViewMenu,
    DeveloperMenu,
    ShowFpsMeter,
    FpsMeter,
    LocalViewMenu,
    Xray,
    ViewPie,
    ShadingPie,
    PieSolid,
    PieWireframe,
    PieMaterialPreview,
    PieTop,
    PieBottom,
    PieFront,
    PieBack,
    PieLeft,
    PieRight,
    PieSelection,
    ViewPerspective,
    ViewFront,
    ViewRight,
    ViewTop,
    ViewBack,
    ViewLeft,
    ViewBottom,
    Edges,
    Grid,
    SnapGrid,
    SnapSpacingMenu,
    SnapAdaptive,
    SnapFixed,
    SnapStep,
    SnapFeedback,
    ZUp,
    Preferences,
    PreferencesWindow,
    PreferencesTitle,
    PreferencesClose,
    AppearanceThemeMenu,
    ThemeSystem,
    ThemeLight,
    ThemeDark,
    AccentColor,
    ResetAccent,
    SettingsJson,
    ReloadSettings,
    PreciseScroll,
    AnimateViews,
    Duration,
    Return3DMenu,
    Return3DPerspective,
    Return3DOrientation,
    Return3DBoth,
    Gizmo,
    GizmoPreferences,
    NavigationPlanar,
    NavigationFree,
    AxisX,
    AxisNegX,
    AxisY,
    AxisNegY,
    AxisZ,
    AxisNegZ,
    Viewport,
    ViewportToolbar,
    EditToolbar,
    StatusBar,
    SceneInfo,
    ToastStack,
    ToastDismiss,
    ToastAction,
    ViewportMenu,
    ViewportFrame,
    FrameSelection,
    ViewportPreferences,
    SelectAll,
    DuplicateSelection,
    DeleteSelection,
    MakeFace,
    Dismiss,
    New,
    Save,
    SaveAs,
    InsertMenu,
    EmptyStateInsert,
    InsertCube,
    InsertCylinder,
    InsertCone,
    InsertTorus,
    InsertPlane,
    InsertCircle,
    InsertSphere,
    InsertPolyhedron,
    ToolView,
    ToolMove,
    ToolRotate,
    ToolScale,
    LeaveEdit,
    Inspector,
    LengthUnitMenu,
    LengthMillimeters,
    LengthCentimeters,
    LengthMeters,
    LengthInches,
    LengthFeet,
    PrimitiveX,
    PrimitiveY,
    PrimitiveZ,
    CircleRadius,
    CircleVertices,
    CircleFill,
    PositionX,
    PositionY,
    PositionZ,
    RotationX,
    RotationY,
    RotationZ,
    ScaleX,
    ScaleY,
    ScaleZ,
    VertexDeltaX,
    VertexDeltaY,
    VertexDeltaZ,
    Segments,
    MinorSegments,
    SphereRings,
    PolyhedronTypeMenu,
    PolyhedronTetrahedron,
    PolyhedronCube,
    PolyhedronOctahedron,
    PolyhedronIcosahedron,
    PolyhedronDodecahedron,
    PolyhedronSize,
    TubeRatio,
    ObjectList,
    LayerRename,
    TransformX,
    TransformY,
    TransformZ,
    TransformXY,
    TransformXZ,
    TransformYZ,
    TransformUniform,
    MoveAxisLock,
    TransformValue,
    Ruler2DHorizontal,
    Ruler2DVertical,
    Ruler2DViewToggle,
    Ruler2DHide,
}

impl Control {
    pub fn id(self) -> &'static str {
        match self {
            Self::ToolDock => "tool-dock",
            Self::TerminalPanelToggle => "terminal.toggle",
            Self::TerminalPanel => "terminal.panel",
            Self::TerminalViewport => "terminal.viewport",
            Self::TerminalStatus => "terminal.status",
            Self::AnimationPanelToggle => "animation.toggle",
            Self::ToolDockTabBar => "tool-dock.tabs",
            Self::ToolDockClose => "tool-dock.close",
            Self::AnimationTimeline => "animation.timeline",
            Self::AnimationRuler => "animation.ruler",
            Self::AnimationFit => "animation.fit",
            Self::SceneHierarchy => "scene.hierarchy",
            Self::ScenePicker => "scene.scene",
            Self::SceneClip => "scene.animation",
            Self::ScenePlay => "scene.play",
            Self::SceneRest => "scene.rest",
            Self::SceneTime => "scene.time",
            Self::SceneLoop => "scene.loop",
            Self::SceneSpeed => "scene.speed",
            Self::SceneCamera => "scene.camera",
            Self::SceneExposure => "scene.exposure",
            Self::SceneDetails => "scene.details",
            Self::SceneDiagnostics => "scene.diagnostics",
            Self::N3Menu => "app.menu",
            Self::FileMenu => "app.file",
            Self::Open => "open",
            Self::Import => "import",
            Self::Frame => "frame",
            Self::Projection => "projection",
            Self::ViewMenu => "view",
            Self::DeveloperMenu => "view.developer",
            Self::ShowFpsMeter => "view.fps-meter.toggle",
            Self::FpsMeter => "developer.fps-meter",
            Self::LocalViewMenu => "view.local-view",
            Self::Xray => "view.xray",
            Self::ViewPie => "view-pie",
            Self::ShadingPie => "shading-pie",
            Self::PieSolid => "shading-pie.solid",
            Self::PieWireframe => "shading-pie.wireframe",
            Self::PieMaterialPreview => "shading-pie.material-preview",
            Self::PieTop => "view-pie.top",
            Self::PieBottom => "view-pie.bottom",
            Self::PieFront => "view-pie.front",
            Self::PieBack => "view-pie.back",
            Self::PieLeft => "view-pie.left",
            Self::PieRight => "view-pie.right",
            Self::PieSelection => "view-pie.selection",
            Self::ViewPerspective => "view.perspective",
            Self::ViewFront => "view.front",
            Self::ViewRight => "view.right",
            Self::ViewTop => "view.top",
            Self::ViewBack => "view.back",
            Self::ViewLeft => "view.left",
            Self::ViewBottom => "view.bottom",
            Self::Edges => "edges",
            Self::Grid => "grid",
            Self::SnapGrid => "snapping.grid",
            Self::SnapSpacingMenu => "snapping.spacing",
            Self::SnapAdaptive => "snapping.adaptive",
            Self::SnapFixed => "snapping.fixed",
            Self::SnapStep => "snapping.step",
            Self::SnapFeedback => "snapping.feedback",
            Self::ZUp => "z-up",
            Self::Preferences => "preferences.open",
            Self::PreferencesWindow => "preferences.window",
            Self::PreferencesTitle => "preferences.title",
            Self::PreferencesClose => "preferences.close",
            Self::AppearanceThemeMenu => "appearance.theme",
            Self::ThemeSystem => "appearance.theme.system",
            Self::ThemeLight => "appearance.theme.light",
            Self::ThemeDark => "appearance.theme.dark",
            Self::AccentColor => "appearance.accent",
            Self::ResetAccent => "appearance.accent.reset",
            Self::SettingsJson => "preferences.settings-json",
            Self::ReloadSettings => "preferences.reload-settings",
            Self::PreciseScroll => "help.precise-scroll",
            Self::AnimateViews => "help.animate",
            Self::Duration => "help.duration",
            Self::Return3DMenu => "gizmo.return-3d",
            Self::Return3DPerspective => "gizmo.return-3d.perspective",
            Self::Return3DOrientation => "gizmo.return-3d.orientation",
            Self::Return3DBoth => "gizmo.return-3d.both",
            Self::Gizmo => "gizmo",
            Self::GizmoPreferences => "gizmo.preferences",
            Self::NavigationPlanar => "gizmo.planar",
            Self::NavigationFree => "gizmo.free",
            Self::AxisX => "gizmo.x",
            Self::AxisNegX => "gizmo.-x",
            Self::AxisY => "gizmo.y",
            Self::AxisNegY => "gizmo.-y",
            Self::AxisZ => "gizmo.z",
            Self::AxisNegZ => "gizmo.-z",
            Self::Viewport => "viewport",
            Self::ViewportToolbar => "viewport.toolbar",
            Self::EditToolbar => "viewport.edit-toolbar",
            Self::StatusBar => "status-bar",
            Self::SceneInfo => "viewport.info",
            Self::ToastStack => "toast.stack",
            Self::ToastDismiss => "toast.dismiss",
            Self::ToastAction => "toast.action",
            Self::ViewportMenu => "viewport.menu",
            Self::ViewportFrame => "viewport.frame",
            Self::FrameSelection => "frame-selection",
            Self::ViewportPreferences => "viewport.preferences",
            Self::SelectAll => "selection.all",
            Self::DuplicateSelection => "selection.duplicate",
            Self::DeleteSelection => "selection.delete",
            Self::MakeFace => "mesh.make-face",
            Self::Dismiss => "dismiss",
            Self::New => "document.new",
            Self::Save => "document.save",
            Self::SaveAs => "document.save-as",
            Self::InsertMenu => "insert",
            Self::EmptyStateInsert => "viewport.empty-insert",
            Self::InsertCube => "insert.cube",
            Self::InsertCylinder => "insert.cylinder",
            Self::InsertCone => "insert.cone",
            Self::InsertTorus => "insert.torus",
            Self::InsertPlane => "insert.plane",
            Self::InsertCircle => "insert.circle",
            Self::InsertSphere => "insert.sphere",
            Self::InsertPolyhedron => "insert.polyhedron",
            Self::ToolView => "tool.view",
            Self::ToolMove => "tool.move",
            Self::ToolRotate => "tool.rotate",
            Self::ToolScale => "tool.scale",
            Self::LeaveEdit => "edit.leave",
            Self::Inspector => "inspector",
            Self::LengthUnitMenu => "length.unit",
            Self::LengthMillimeters => "length.mm",
            Self::LengthCentimeters => "length.cm",
            Self::LengthMeters => "length.m",
            Self::LengthInches => "length.in",
            Self::LengthFeet => "length.ft",
            Self::PrimitiveX => "primitive.x",
            Self::PrimitiveY => "primitive.y",
            Self::PrimitiveZ => "primitive.z",
            Self::CircleRadius => "primitive.circle.radius",
            Self::CircleVertices => "primitive.circle.vertices",
            Self::CircleFill => "primitive.circle.fill",
            Self::PositionX => "property.position.x",
            Self::PositionY => "property.position.y",
            Self::PositionZ => "property.position.z",
            Self::RotationX => "property.rotation.x",
            Self::RotationY => "property.rotation.y",
            Self::RotationZ => "property.rotation.z",
            Self::ScaleX => "property.scale.x",
            Self::ScaleY => "property.scale.y",
            Self::ScaleZ => "property.scale.z",
            Self::VertexDeltaX => "property.vertex-delta.x",
            Self::VertexDeltaY => "property.vertex-delta.y",
            Self::VertexDeltaZ => "property.vertex-delta.z",
            Self::Segments => "primitive.segments",
            Self::MinorSegments => "primitive.minor-segments",
            Self::SphereRings => "primitive.latitude-rings",
            Self::PolyhedronTypeMenu => "primitive.polyhedron-type",
            Self::PolyhedronTetrahedron => "primitive.polyhedron.tetrahedron",
            Self::PolyhedronCube => "primitive.polyhedron.cube",
            Self::PolyhedronOctahedron => "primitive.polyhedron.octahedron",
            Self::PolyhedronIcosahedron => "primitive.polyhedron.icosahedron",
            Self::PolyhedronDodecahedron => "primitive.polyhedron.dodecahedron",
            Self::PolyhedronSize => "primitive.polyhedron.size",
            Self::TubeRatio => "primitive.tube-ratio",
            Self::ObjectList => "objects",
            Self::LayerRename => "layer.rename",
            Self::TransformX => "transform.x",
            Self::TransformY => "transform.y",
            Self::TransformZ => "transform.z",
            Self::TransformXY => "transform.xy",
            Self::TransformXZ => "transform.xz",
            Self::TransformYZ => "transform.yz",
            Self::TransformUniform => "transform.uniform",
            Self::MoveAxisLock => "move.axis-lock",
            Self::TransformValue => "transform.value",
            Self::Ruler2DHorizontal => "2d-ruler.horizontal",
            Self::Ruler2DVertical => "2d-ruler.vertical",
            Self::Ruler2DViewToggle => "view.2d-ruler",
            Self::Ruler2DHide => "2d-ruler.hide",
        }
    }
    pub fn label(self) -> &'static str {
        match self {
            Self::ToolDock => "Tool Dock",
            Self::TerminalPanelToggle => crate::input::actions::ActionId::TerminalPanel.label(),
            Self::TerminalPanel => "Terminal panel",
            Self::TerminalViewport => "Terminal contents",
            Self::TerminalStatus => "Terminal status",
            Self::AnimationPanelToggle => crate::input::actions::ActionId::AnimationPanel.label(),
            Self::ToolDockTabBar => "Tool Dock tab bar",
            Self::ToolDockClose => "Close Tool Dock",
            Self::AnimationTimeline => "Animation timeline",
            Self::AnimationRuler => "Time ruler",
            Self::AnimationFit => "Fit",
            Self::SceneHierarchy => "Scene hierarchy",
            Self::ScenePicker => "Scene",
            Self::SceneClip => "Animation",
            Self::ScenePlay => "Play / pause",
            Self::SceneRest => "Rest pose",
            Self::SceneTime => "Time",
            Self::SceneLoop => "Loop",
            Self::SceneSpeed => "Speed",
            Self::SceneCamera => "Camera",
            Self::SceneExposure => "Exposure",
            Self::SceneDetails => "Scene details",
            Self::SceneDiagnostics => "Compatibility",
            Self::N3Menu => "N3",
            Self::FileMenu => "File",
            Self::Open => crate::input::actions::ActionId::Open.label(),
            Self::Import => crate::input::actions::ActionId::Import.label(),
            Self::Frame => "Frame",
            Self::Projection => "Projection",
            Self::ViewMenu => "View",
            Self::DeveloperMenu => "Developer",
            Self::ShowFpsMeter => crate::input::actions::ActionId::ToggleFpsMeter.label(),
            Self::FpsMeter => "App FPS Meter",
            Self::LocalViewMenu => crate::input::actions::ActionId::LocalView.label(),
            Self::Xray => crate::input::actions::ActionId::Xray.label(),
            Self::ViewPie => "View",
            Self::ShadingPie => "Shading",
            Self::PieSolid => "Solid",
            Self::PieWireframe => "Wireframe",
            Self::PieMaterialPreview => "Material Preview",
            Self::PieTop => "Top",
            Self::PieBottom => "Bottom",
            Self::PieFront => "Front",
            Self::PieBack => "Back",
            Self::PieLeft => "Left",
            Self::PieRight => "Right",
            Self::PieSelection => "Frame selection",
            Self::ViewPerspective => crate::input::actions::ActionId::ViewPerspective.label(),
            Self::ViewFront => crate::input::actions::ActionId::ViewFront.label(),
            Self::ViewRight => crate::input::actions::ActionId::ViewRight.label(),
            Self::ViewTop => crate::input::actions::ActionId::ViewTop.label(),
            Self::ViewBack => crate::input::actions::ActionId::ViewBack.label(),
            Self::ViewLeft => crate::input::actions::ActionId::ViewLeft.label(),
            Self::ViewBottom => crate::input::actions::ActionId::ViewBottom.label(),
            Self::Edges => crate::input::actions::ActionId::Edges.label(),
            Self::Grid => "Grid",
            Self::SnapGrid => "Snap movement to grid",
            Self::SnapSpacingMenu => "Movement spacing",
            Self::SnapAdaptive => "Auto",
            Self::SnapFixed => "Fixed",
            Self::SnapStep => "Fixed step (cm)",
            Self::SnapFeedback => "Movement snap",
            Self::ZUp => "Z-up",
            Self::Preferences | Self::PreferencesWindow | Self::PreferencesTitle => {
                crate::input::actions::ActionId::Preferences.label()
            }
            Self::PreferencesClose => "Close",
            Self::AppearanceThemeMenu => "Theme",
            Self::ThemeSystem => "System",
            Self::ThemeLight => "Light",
            Self::ThemeDark => "Dark",
            Self::AccentColor => "Accent color",
            Self::ResetAccent => "Reset accent",
            Self::SettingsJson => "Open settings.json",
            Self::ReloadSettings => "Reload settings",
            Self::PreciseScroll => "Precise scroll zooms (for Magic Mouse)",
            Self::AnimateViews => "Animate view changes",
            Self::Duration => "Duration",
            Self::Return3DMenu => "Return to 3D",
            Self::Return3DPerspective => "Perspective only",
            Self::Return3DOrientation => "Previous orientation",
            Self::Return3DBoth => "Previous orientation + perspective",
            Self::Gizmo => "Axis gizmo",
            Self::GizmoPreferences => "Gizmo preferences…",
            Self::NavigationPlanar => "2D",
            Self::NavigationFree => "3D",
            Self::AxisX => "X",
            Self::AxisNegX => "−X",
            Self::AxisY => "Y",
            Self::AxisNegY => "−Y",
            Self::AxisZ => "Z",
            Self::AxisNegZ => "−Z",
            Self::Viewport => "Viewport",
            Self::ViewportToolbar => "Tools",
            Self::EditToolbar => "Editing object",
            Self::StatusBar => "Status bar",
            Self::SceneInfo => "Scene information",
            Self::ToastStack => "Toasts",
            Self::ToastDismiss => "Dismiss notification",
            Self::ToastAction => "Notification action",
            Self::ViewportMenu => "Viewport",
            Self::ViewportFrame => crate::input::actions::ActionId::FrameAll.label(),
            Self::FrameSelection => crate::input::actions::ActionId::FrameSelection.label(),
            Self::ViewportPreferences => crate::input::actions::ActionId::Preferences.label(),
            Self::SelectAll => crate::input::actions::ActionId::SelectAll.label(),
            Self::DuplicateSelection => crate::input::actions::ActionId::Duplicate.label(),
            Self::DeleteSelection => crate::input::actions::ActionId::Delete.label(),
            Self::MakeFace => crate::input::actions::ActionId::MakeFace.label(),
            Self::Dismiss => "Dismiss",
            Self::New => crate::input::actions::ActionId::New.label(),
            Self::Save => crate::input::actions::ActionId::Save.label(),
            Self::SaveAs => crate::input::actions::ActionId::SaveAs.label(),
            Self::InsertMenu => "Insert",
            Self::EmptyStateInsert => "Insert a shape",
            Self::InsertCube => crate::input::actions::ActionId::InsertCube.label(),
            Self::InsertCylinder => crate::input::actions::ActionId::InsertCylinder.label(),
            Self::InsertCone => crate::input::actions::ActionId::InsertCone.label(),
            Self::InsertTorus => crate::input::actions::ActionId::InsertTorus.label(),
            Self::InsertPlane => crate::input::actions::ActionId::InsertPlane.label(),
            Self::InsertCircle => crate::input::actions::ActionId::InsertCircle.label(),
            Self::InsertSphere => crate::input::actions::ActionId::InsertSphere.label(),
            Self::InsertPolyhedron => crate::input::actions::ActionId::InsertPolyhedron.label(),
            Self::ToolView => "Cursor",
            Self::ToolMove => "Move",
            Self::ToolRotate => "Rotate",
            Self::ToolScale => "Scale",
            Self::LeaveEdit => "Exit edit mode",
            Self::Inspector => "Properties",
            Self::LengthUnitMenu => "Display unit",
            Self::LengthMillimeters => "Millimeters (mm)",
            Self::LengthCentimeters => "Centimeters (cm)",
            Self::LengthMeters => "Meters (m)",
            Self::LengthInches => "Inches (in)",
            Self::LengthFeet => "Feet (ft)",
            Self::PrimitiveX => "Width",
            Self::PrimitiveY => "Height",
            Self::PrimitiveZ => "Depth",
            Self::CircleRadius => "Radius",
            Self::CircleVertices => "Vertices",
            Self::CircleFill => "Fill",
            Self::PositionX => "Position X",
            Self::PositionY => "Position Y",
            Self::PositionZ => "Position Z",
            Self::RotationX => "Rotation X",
            Self::RotationY => "Rotation Y",
            Self::RotationZ => "Rotation Z",
            Self::ScaleX => "Scale X",
            Self::ScaleY => "Scale Y",
            Self::ScaleZ => "Scale Z",
            Self::VertexDeltaX => "Vertex movement X",
            Self::VertexDeltaY => "Vertex movement Y",
            Self::VertexDeltaZ => "Vertex movement Z",
            Self::Segments => "Segments",
            Self::MinorSegments => "Tube segments",
            Self::SphereRings => "Latitude rings",
            Self::PolyhedronTypeMenu => "Polyhedron type",
            Self::PolyhedronTetrahedron => PolyhedronType::Tetrahedron.label(),
            Self::PolyhedronCube => PolyhedronType::Cube.label(),
            Self::PolyhedronOctahedron => PolyhedronType::Octahedron.label(),
            Self::PolyhedronIcosahedron => PolyhedronType::Icosahedron.label(),
            Self::PolyhedronDodecahedron => PolyhedronType::Dodecahedron.label(),
            Self::PolyhedronSize => "Polyhedron size",
            Self::TubeRatio => "Tube ratio",
            Self::ObjectList => "Layers",
            Self::LayerRename => "Rename layer",
            Self::TransformX => "X",
            Self::TransformY => "Y",
            Self::TransformZ => "Z",
            Self::TransformXY => "XY",
            Self::TransformXZ => "XZ",
            Self::TransformYZ => "YZ",
            Self::TransformUniform => "Uniform scale",
            Self::MoveAxisLock => "Transform axis lock",
            Self::TransformValue => "Transform value",
            Self::Ruler2DHorizontal => "Horizontal 2D ruler",
            Self::Ruler2DVertical => "Vertical 2D ruler",
            Self::Ruler2DViewToggle => crate::input::actions::ActionId::Ruler2D.label(),
            Self::Ruler2DHide => "Hide 2D ruler",
        }
    }
}

pub fn shortcut_label(id: &str) -> String {
    crate::input::bindings::binding(id)
        .expect("UI shortcut must be registered in the input bindings")
        .label()
}

/// Extend menu dividers through the popup frame's content padding.
pub fn menu_separator(ui: &mut egui::Ui) -> egui::Response {
    ui.add(egui::Separator::default().grow(f32::from(ui.spacing().menu_margin.left)))
}

/// N3's default submenu row. Keep icon and sizing policy out of menu call sites.
pub fn submenu_button(control: Control) -> egui::containers::menu::SubMenuButton<'static> {
    egui::containers::menu::SubMenuButton::from_button(
        egui::Button::new(control.label())
            .right_text(super::lucide::Icon::ChevronRight.text(crate::theme::text::BASE))
            .min_size(egui::vec2(crate::theme::size::STEP_52, 0.0)),
    )
}

pub fn button(ui: &mut egui::Ui, control: Control) -> egui::Response {
    button_enabled(ui, control, true)
}

pub fn button_enabled(ui: &mut egui::Ui, control: Control, enabled: bool) -> egui::Response {
    button_enabled_min_width(ui, control, enabled, 0.0)
}

pub fn button_enabled_min_width(
    ui: &mut egui::Ui,
    control: Control,
    enabled: bool,
    min_width: f32,
) -> egui::Response {
    let mut button = egui::Button::new(control.label());
    button = button.min_size(egui::vec2(min_width, 0.0));
    let response = ui.add_enabled(enabled, button);
    record(
        ui.ctx(),
        control,
        control.label(),
        response.rect,
        response.enabled(),
    );
    response
}
pub fn checkbox(ui: &mut egui::Ui, control: Control, value: &mut bool) -> egui::Response {
    let response = ui.checkbox(value, control.label());
    record(
        ui.ctx(),
        control,
        control.label(),
        response.rect,
        response.enabled(),
    );
    response
}

#[cfg(test)]
mod tests {
    use super::*;
    fn rect() -> egui::Rect {
        egui::Rect::from_min_size(egui::Pos2::ZERO, egui::vec2(20., 20.))
    }
    #[test]
    fn catalog_ids_are_unique_and_unknown_ids_fail() {
        let ids: std::collections::BTreeSet<_> =
            Control::ALL.map(Control::id).into_iter().collect();
        assert_eq!(ids.len(), Control::ALL.len());
        assert!(Control::parse("removed.save").is_err());
    }
    #[test]
    fn paths_follow_actual_scope_and_displayed_label() {
        let ctx = egui::Context::default();
        enable(&ctx);
        record(&ctx, Control::PreferencesWindow, "Settings", rect(), true);
        scope(&ctx, Control::PreferencesWindow, || {
            record(&ctx, Control::AnimateViews, "Animate", rect(), true)
        });
        assert_eq!(
            snapshot(&ctx).path(Control::AnimateViews).unwrap(),
            "Settings → Animate"
        );
        begin_pass(&ctx);
        record(&ctx, Control::AnimateViews, "Animate", rect(), true);
        assert_eq!(
            snapshot(&ctx).path(Control::AnimateViews).unwrap(),
            "Animate"
        );
    }
    #[test]
    fn missing_and_duplicate_controls_fail_instead_of_falling_back_to_catalog() {
        let ctx = egui::Context::default();
        enable(&ctx);
        assert!(snapshot(&ctx).path(Control::Frame).is_err());
        record(&ctx, Control::Frame, "Frame", rect(), true);
        record(&ctx, Control::Frame, "Frame", rect(), true);
        assert!(
            snapshot(&ctx)
                .get(Control::Frame)
                .unwrap_err()
                .contains("Ambiguous")
        );
    }
}
