//! Executable user documentation: one production UI, one required verification path.
use crate::{
    controls::{self, Control, Trace},
    doc_capture::Capture,
    doc_input::VirtualInput,
    document,
    keyboard_input::{NumberKey, NumberKeyEvent},
    navigation_events::{self, Event as NavigationEvent},
    shortcuts::{HostEffect, ShortcutFrame},
    workspace_ui::{self, SavedLayout, WorkspaceUi},
};
pub(crate) mod animation;
mod artifacts;
pub(crate) mod capture;
mod features;
pub(crate) mod input;
mod shortcut_replay;
pub use artifacts::run;
use artifacts::{insert, validate_path};
use features::FEATURES;

use std::{
    collections::{BTreeMap, BTreeSet},
    path::{Path, PathBuf},
    time::Duration,
};

#[cfg(test)]
#[path = "tests/axis_lock_tests.rs"]
mod axis_lock_tests;
#[path = "scenarios/axis_locks.rs"]
mod axis_locks;
#[path = "scenarios/edit_selection.rs"]
mod edit_selection;
#[cfg(test)]
#[path = "tests/edit_toolbar_tests.rs"]
mod edit_toolbar_tests;
#[path = "scenarios/editing.rs"]
mod editing;
#[path = "scenarios/gizmo.rs"]
mod gizmo;
#[path = "scenarios/hand_tool.rs"]
mod hand_tool;
#[cfg(test)]
#[path = "tests/insert_menu_tests.rs"]
mod insert_menu_tests;
#[path = "scenarios/length_units.rs"]
mod length_units;
#[path = "scenarios/local_view.rs"]
mod local_view;
#[path = "scenarios/make_face.rs"]
mod make_face;
#[cfg(test)]
#[path = "tests/make_face_input_tests.rs"]
mod make_face_input_tests;
#[path = "scenarios/navigation.rs"]
mod navigation;
#[cfg(test)]
#[path = "tests/numeric_input_tests.rs"]
mod numeric_input_tests;
#[path = "scenarios/numeric_transforms.rs"]
mod numeric_transforms;
#[path = "scenarios/object_feedback.rs"]
mod object_feedback;
#[path = "scenarios/opening_models.rs"]
mod opening_models;
#[path = "scenarios/orbit_tool.rs"]
mod orbit_tool;
#[cfg(test)]
#[path = "tests/orbit_tool_tests.rs"]
mod orbit_tool_tests;
#[path = "scenarios/2d_ruler.rs"]
mod ruler_2d;
#[path = "scenarios/selection_keys.rs"]
mod selection_keys;
#[path = "scenarios/settings.rs"]
mod settings;
#[path = "scenarios/shading.rs"]
mod shading;
#[cfg(test)]
#[path = "tests/shading_tests.rs"]
mod shading_tests;
#[path = "scenarios/snapping.rs"]
mod snapping;
#[cfg(test)]
#[path = "tests/toast_tests.rs"]
mod toast_tests;
#[path = "scenarios/toasts.rs"]
mod toasts;
#[path = "scenarios/2d.rs"]
mod two_d;
#[path = "scenarios/view_keys.rs"]
mod view_keys;
#[path = "scenarios/view_pie.rs"]
mod view_pie;
#[cfg(test)]
#[path = "tests/view_pie_tests.rs"]
mod view_pie_tests;
#[path = "scenarios/workspace.rs"]
mod workspace;
#[path = "scenarios/xray.rs"]
mod xray;
#[cfg(test)]
#[path = "tests/xray_input_tests.rs"]
mod xray_input_tests;

mod annotations;

mod tutorial;
pub use tutorial::ClipSpec;

pub type Result<T> = std::result::Result<T, String>;
#[cfg(test)]
#[path = "tests/doc_navigation_tests.rs"]
mod doc_navigation_tests;
type Artifacts = BTreeMap<String, Vec<u8>>;
// Keep the actual editor canvas spacious at Full HD resolution. The shared
// documentation frame adds its window chrome around this unscaled capture.
const WIDTH: u32 = 1920;
const HEIGHT: u32 = 1080;
const GENERATED: &str = "<!-- Generated by `just docs update`; edit docs/templates/*.md.in and src/documentation/scenarios/*.rs. -->\n\n";

/// Scenario key/pointer helpers carry modifiers on each event. egui also needs
/// explicit modifier transitions, just like egui-winit emits for native input.
/// Insert those transitions without losing the source metadata for numpad keys.
fn normalize_replay_events(
    events: Vec<egui::Event>,
    mut numbers: Vec<NumberKeyEvent>,
    initial_modifiers: egui::Modifiers,
    navigation_modifiers: Option<egui::Modifiers>,
) -> Result<(Vec<egui::Event>, Vec<NumberKeyEvent>, egui::Modifiers)> {
    let mut normalized = Vec::with_capacity(events.len() + 1);
    let mut original_indices = Vec::with_capacity(events.len());
    let mut modifiers = initial_modifiers;
    // A native navigation helper contributes its one gesture event. Zoom and
    // Rotate have no embedded modifiers, so emit its host transition first.
    if let Some(next) = navigation_modifiers
        && next != modifiers
    {
        normalized.push(egui::Event::ModifiersChanged(next));
        modifiers = next;
    }
    for event in events {
        match &event {
            egui::Event::Key {
                modifiers: next, ..
            }
            | egui::Event::PointerButton {
                modifiers: next, ..
            }
            | egui::Event::MouseWheel {
                modifiers: next, ..
            } if *next != modifiers => {
                normalized.push(egui::Event::ModifiersChanged(*next));
                modifiers = *next;
            }
            egui::Event::ModifiersChanged(next) => modifiers = *next,
            egui::Event::WindowFocused(false) => modifiers = egui::Modifiers::NONE,
            _ => {}
        }
        original_indices.push(normalized.len());
        normalized.push(event);
    }
    for number in &mut numbers {
        number.event_index = *original_indices
            .get(number.event_index)
            .ok_or("Number-key metadata points outside the documentation event queue")?;
    }
    Ok((normalized, numbers, modifiers))
}

pub struct Session<'a> {
    pub state: WorkspaceUi,
    pub trace: Trace,
    pub values: BTreeMap<String, String>,
    pub input: VirtualInput,
    pub cursor: egui::CursorIcon,
    ctx: egui::Context,
    capture: &'a mut Capture,
    bindings: BTreeMap<Control, String>,
    shortcut_bindings: BTreeMap<String, String>,
    images: Artifacts,
    image_inputs: BTreeMap<String, String>,
    facts: Vec<String>,
    time: f64,
    focused: bool,
    number_keys_down: BTreeSet<NumberKey>,
    uploaded_revision: u64,
    show_inputs: bool,
    annotations: Vec<annotations::Annotation>,
    recorder: Option<tutorial::Recorder>,
    animations: BTreeSet<String>,
    #[cfg(test)]
    extra_layout_pass: bool,
}

impl<'a> Session<'a> {
    fn new(capture: &'a mut Capture) -> Result<Self> {
        capture.scene.clear_mesh();
        let ctx = egui::Context::default();
        // The guide documents the Mac application even when its canonical
        // pixels are rendered on Linux. Keep egui's key labels and behavior fixed.
        ctx.set_os(egui::os::OperatingSystem::Mac);
        workspace_ui::configure_context(&ctx);
        controls::enable(&ctx);
        let mut state = WorkspaceUi::new(capture.texture);
        // Guide captures use a host-independent Light baseline. The settings
        // scenario switches themes through the real preference UI to show both.
        state.theme_mode = crate::settings::ThemeMode::Light;
        state.apply_saved_layout(&ctx, SavedLayout::DOCUMENTATION);
        let mut session = Self {
            state,
            trace: Trace::default(),
            values: BTreeMap::new(),
            input: VirtualInput::default(),
            cursor: egui::CursorIcon::Default,
            ctx,
            capture,
            bindings: BTreeMap::new(),
            shortcut_bindings: BTreeMap::new(),
            images: BTreeMap::new(),
            image_inputs: BTreeMap::new(),
            facts: Vec::new(),
            time: 0.,
            focused: true,
            number_keys_down: BTreeSet::new(),
            uploaded_revision: u64::MAX,
            show_inputs: true,
            annotations: Vec::new(),
            recorder: None,
            animations: BTreeSet::new(),
            #[cfg(test)]
            extra_layout_pass: false,
        };
        session.settle()?;
        // egui Areas fade in on their first visible frame. Finish that startup
        // transition on the explicit scenario clock before a feature starts;
        // captures and later settle() calls must remain time-free.
        let animation_seconds = session.ctx.global_style().animation_time;
        if !animation_seconds.is_finite() || animation_seconds < 0.0 {
            return Err(
                "Documentation startup animation duration must be finite and nonnegative".into(),
            );
        }
        let warmup_ms = (f64::from(animation_seconds) * 1000.0).ceil() as u64;
        session.frame(Vec::new(), Duration::from_millis(warmup_ms))?;
        session.settle()?;
        if session.ctx.theme() != egui::Theme::Light
            || session.state.resolved_theme() != crate::settings::ResolvedTheme::Light
        {
            return Err("Documentation capture did not resolve the explicit Light baseline".into());
        }
        let layout = session.state.save_layout(&session.ctx);
        let expected = SavedLayout::DOCUMENTATION;
        if !session.state.show_ui
            || (layout.hierarchy_width - expected.hierarchy_width).abs() > 1.0
            || (layout.inspector_width - expected.inspector_width).abs() > 1.0
        {
            return Err(format!(
                "Documentation capture did not apply the standard panel layout: {layout:?}"
            ));
        }
        Ok(session)
    }
    pub fn frame(&mut self, events: Vec<egui::Event>, elapsed: Duration) -> Result<bool> {
        self.frame_with_numbers(events, elapsed, Vec::new())
    }
    /// Deliver one host gesture at the current pointer. The event drives both
    /// production navigation and its cue; UI ownership can reject its effect.
    pub fn navigation(&mut self, event: NavigationEvent, elapsed: Duration) -> Result<()> {
        let events = event.egui_event().into_iter().collect();
        self.frame_with_navigation(events, elapsed, Vec::new(), Some(event))?;
        self.settle()
    }
    pub fn scroll(
        &mut self,
        dx: f32,
        dy: f32,
        precise: bool,
        modifiers: egui::Modifiers,
    ) -> Result<()> {
        let delta = egui::vec2(dx, dy);
        let event = if precise {
            NavigationEvent::TrackpadScroll {
                delta,
                phase: crate::scroll_input::ScrollPhase::Moved,
                modifiers,
            }
        } else {
            NavigationEvent::Wheel { delta, modifiers }
        };
        self.navigation(event, Duration::ZERO)
    }
    pub fn trackpad_scroll(
        &mut self,
        dx: f32,
        dy: f32,
        modifiers: egui::Modifiers,
        phase: crate::scroll_input::ScrollPhase,
    ) -> Result<()> {
        self.navigation(
            NavigationEvent::TrackpadScroll {
                delta: egui::vec2(dx, dy),
                phase,
                modifiers,
            },
            Duration::ZERO,
        )
    }
    pub fn pinch(&mut self, delta: f64) -> Result<()> {
        self.navigation(
            NavigationEvent::Pinch {
                delta,
                modifiers: self.input.modifiers(),
            },
            Duration::ZERO,
        )
    }
    pub fn trackpad_rotate(&mut self, degrees: f32) -> Result<()> {
        self.navigation(
            NavigationEvent::Rotate {
                degrees,
                modifiers: self.input.modifiers(),
            },
            Duration::ZERO,
        )
    }
    pub fn modifiers_changed(&mut self, modifiers: egui::Modifiers) -> Result<()> {
        self.navigation(NavigationEvent::ModifiersChanged(modifiers), Duration::ZERO)
    }
    fn frame_with_numbers(
        &mut self,
        events: Vec<egui::Event>,
        elapsed: Duration,
        numbers: Vec<NumberKeyEvent>,
    ) -> Result<bool> {
        self.frame_with_navigation(events, elapsed, numbers, None)
    }
    fn frame_with_navigation(
        &mut self,
        events: Vec<egui::Event>,
        elapsed: Duration,
        numbers: Vec<NumberKeyEvent>,
        navigation: Option<NavigationEvent>,
    ) -> Result<bool> {
        self.record_elapsed(elapsed)?;
        self.time += elapsed.as_secs_f64();
        self.state.camera.advance_transition(elapsed);
        for event in &events {
            if let egui::Event::WindowFocused(focused) = event {
                self.focused = *focused;
                if !focused {
                    self.number_keys_down.clear();
                }
            }
        }
        let (events, numbers, modifiers) = normalize_replay_events(
            events,
            numbers,
            self.input.modifiers(),
            navigation.map(NavigationEvent::modifiers),
        )?;
        self.input.advance(elapsed);
        for event in &events {
            match event {
                egui::Event::ModifiersChanged(modifiers) => {
                    self.state.navigation_modifiers_changed(*modifiers);
                }
                egui::Event::WindowFocused(false) => {
                    self.state
                        .navigation_modifiers_changed(egui::Modifiers::NONE);
                }
                _ => {}
            }
        }
        self.input
            .observe(&events, &numbers, modifiers, self.focused);
        if let Some(event) = navigation {
            navigation_events::route(
                &mut self.state,
                &self.ctx,
                self.input.position(),
                self.focused,
                &events,
                event,
            );
        }
        let input = egui::RawInput {
            screen_rect: Some(egui::Rect::from_min_size(
                egui::Pos2::ZERO,
                egui::vec2(WIDTH as f32, HEIGHT as f32),
            )),
            time: Some(self.time),
            predicted_dt: 1. / 60.,
            events,
            focused: self.focused,
            ..Default::default()
        };
        let mut open = false;
        let mut annotation_result = Ok(());
        let mut shortcuts = ShortcutFrame::with_number_events(&self.ctx, numbers);
        let context = self.ctx.clone();
        let mut output = context.run_ui(input, |ui| {
            let context = ui.ctx().clone();
            let ctx = &context;
            shortcuts.begin_pass(ctx);
            open |= self.state.ui(ui);
            shortcuts
                .collect_with_transform(ctx, self.state.transform_keyboard_context(ctx, false));
            self.cursor = ctx.output(|output| output.cursor_icon);
            annotation_result = self.paint_annotations(ctx);
            if self.show_inputs {
                self.input.paint(ctx, self.state.viewport, self.cursor);
            }
            #[cfg(test)]
            if self.extra_layout_pass && ctx.current_pass_index() == 0 {
                ctx.request_discard("Exercise documentation input across a layout retry");
            }
        });
        // A failed scenario discards this frame intentionally. egui requires
        // every texture delta to be consumed or explicitly discarded, including
        // on validation errors before the compositor receives the output.
        annotation_result.inspect_err(|_| output.textures_delta.clear())?;
        #[cfg(test)]
        {
            self.extra_layout_pass = false;
        }
        for command in self
            .state
            .take_ui_commands()
            .into_iter()
            .chain(shortcuts.commands())
        {
            open |= self.state.dispatch(command, &self.ctx, false) == HostEffect::Open;
            if egui::Popup::is_any_open(&self.ctx) {
                // Match native ownership when a command opens a popup.
                break;
            }
        }
        // New is deterministic in a fresh scenario; destructive native prompts
        // and save destinations remain explicit host-effect boundaries.
        if self.state.request_new && !self.state.is_dirty() {
            self.state.request_new = false;
            self.state.new_document();
        }
        self.state
            .refresh_mesh()
            .inspect_err(|_| output.textures_delta.clear())?;
        if self.uploaded_revision != self.state.mesh_revision {
            if let Some(mesh) = &self.state.mesh {
                self.capture.scene.set_mesh(&self.capture.device, mesh);
            } else {
                self.capture.scene.clear_mesh();
            }
            self.uploaded_revision = self.state.mesh_revision;
        }
        self.trace = controls::snapshot(&self.ctx);
        self.trace
            .validate()
            .inspect_err(|_| output.textures_delta.clear())?;
        self.capture
            .scene
            .set_visible_objects(self.state.visible_objects());
        self.capture
            .scene
            .set_highlights(self.state.object_highlights());
        self.capture
            .scene
            .set_edit_selection(&self.capture.device, self.state.edit_selection());
        self.capture.scene.set_pixel_scale(1.0);
        let gizmo = self
            .state
            .editor
            .transform_gizmo_vertices(self.state.viewport, &self.state.camera, self.state.z_up)
            .inspect_err(|_| output.textures_delta.clear())?;
        self.capture
            .scene
            .set_transform_gizmo(&self.capture.queue, gizmo);
        self.capture.render(
            &self.ctx,
            output,
            self.state.viewport,
            &self.state.camera,
            self.state.shading,
            self.state.editor.xray_enabled(),
            self.state.show_edges,
            self.state.show_grid,
            self.state.z_up,
            crate::theme::Palette::new(self.state.resolved_theme(), self.state.accent_color)
                .workbench_viewport,
        )?;
        Ok(open)
    }
    pub fn settle(&mut self) -> Result<()> {
        // Egui uses previous-frame geometry for hit testing and popup layout.
        // No wall-clock sleep or animation advancement is hidden here.
        self.frame(Vec::new(), Duration::ZERO)?;
        self.frame(Vec::new(), Duration::ZERO)?;
        Ok(())
    }
    pub fn load_fixture(&mut self, name: &str) -> Result<()> {
        if Path::new(name).file_name().and_then(|s| s.to_str()) != Some(name) {
            return Err("Fixture must be a filename".into());
        }
        let path = root().join("fixtures/obj").join(name);
        let document = document::load(&path)?;
        self.state.install_document(path, document)?;
        self.settle()
    }
    pub fn witness(&mut self, control: Control) -> Result<()> {
        let path = self.trace.path(control)?;
        self.bindings.insert(control, path);
        Ok(())
    }
    fn target(&mut self, control: Control) -> Result<egui::Pos2> {
        self.witness(control)?;
        let item = self.trace.get(control)?;
        if !item.enabled {
            return Err(format!("Control {} is disabled", control.id()));
        }
        if !item.rect.is_positive() {
            return Err(format!("Control {} has no hit area", control.id()));
        }
        Ok(item.rect.center())
    }
    pub fn click(&mut self, control: Control) -> Result<bool> {
        let pos = self.target(control)?;
        self.click_at(pos)
    }

    /// Close Preferences through its semantic Escape action. The footer action
    /// may be below the scroll viewport in a compact window.
    pub fn close_preferences(&mut self) -> Result<()> {
        self.witness(Control::PreferencesWindow)?;
        self.shortcut("cancel")?;
        self.require(
            !self.state.show_preferences,
            "Escape closes Preferences before returning to viewport interactions",
        )
    }

    /// Scroll the real Preferences content until a recorded control is inside
    /// the window. Layout changes can place otherwise-live controls below the
    /// scroll viewport; replay must not click their offscreen response rects.
    pub fn reveal_preferences_control(&mut self, control: Control) -> Result<()> {
        self.witness(Control::PreferencesWindow)?;
        if control == Control::PreferencesClose {
            let window = self.trace.get(Control::PreferencesWindow)?.rect;
            let close = self.trace.get(control)?.rect;
            return self.require(
                window.contains_rect(close),
                "The fixed Preferences close button remains inside its window",
            );
        }
        for _ in 0..6 {
            let window = self.trace.get(Control::PreferencesWindow)?.rect;
            let target = self.trace.get(control)?.rect;
            let content_top = window.top() + 50.0;
            let content_bottom = window.bottom() - 16.0;
            if target.top() >= content_top && target.bottom() <= content_bottom {
                return Ok(());
            }
            let delta = if target.top() < content_top {
                (content_top - target.top() + 24.0).max(60.0)
            } else {
                -(target.bottom() - content_bottom + 24.0).max(60.0)
            };
            self.hover(Control::PreferencesWindow)?;
            self.scroll(0.0, delta, true, egui::Modifiers::NONE)?;
            self.wait(Duration::from_millis(350))?;
        }
        Err(format!(
            "Preferences control {} stayed outside the scroll viewport: control={:?} window={:?}",
            control.id(),
            self.trace.get(control)?.rect,
            self.trace.get(Control::PreferencesWindow)?.rect
        ))
    }

    /// Explicit reachability, authored beside the behavior it documents.
    /// Start at the deepest visible member so an already-open menu/window is
    /// not toggled closed. Every subsequent item must appear through a real click.
    pub fn click_path(&mut self, path: &[Control]) -> Result<bool> {
        if path.is_empty() {
            return Err("A documentation click path must contain a target".into());
        }
        let start = path
            .iter()
            .rposition(|control| self.trace.get(*control).is_ok())
            .ok_or_else(|| format!("No visible entry point in click path: {path:?}"))?;
        let mut open = false;
        for control in &path[start..] {
            open |= self.click(*control)?;
        }
        Ok(open)
    }

    pub fn undo(&mut self) -> Result<()> {
        self.shortcut("history.undo").map(|_| ())
    }

    pub fn redo(&mut self) -> Result<()> {
        self.shortcut("history.redo").map(|_| ())
    }
    pub fn right_click(&mut self, control: Control) -> Result<()> {
        let pos = self.target(control)?;
        self.click_button_at(pos, egui::PointerButton::Secondary)?;
        Ok(())
    }
    pub fn hover(&mut self, control: Control) -> Result<()> {
        let pos = self.target(control)?;
        self.frame(vec![egui::Event::PointerMoved(pos)], Duration::ZERO)?;
        self.settle()
    }
    pub fn key(
        &mut self,
        key: egui::Key,
        pressed: bool,
        modifiers: egui::Modifiers,
    ) -> Result<bool> {
        let open = self.frame(
            vec![egui::Event::Key {
                key,
                physical_key: None,
                pressed,
                repeat: false,
                modifiers,
            }],
            Duration::ZERO,
        )?;
        self.settle()?;
        Ok(open)
    }
    /// Reproduce native numeric source metadata without conflating numpad and
    /// top-row keys, including simultaneous holds of the same printed digit.
    pub fn number_key(
        &mut self,
        key: NumberKey,
        pressed: bool,
        modifiers: egui::Modifiers,
    ) -> Result<bool> {
        let logical = key.egui_key().ok_or("Expected a digit from 0 through 9")?;
        let repeat = if pressed {
            !self.number_keys_down.insert(key)
        } else {
            self.number_keys_down.remove(&key);
            false
        };
        let open = self.frame_with_numbers(
            vec![egui::Event::Key {
                key: logical,
                physical_key: Some(logical),
                pressed,
                repeat,
                modifiers,
            }],
            Duration::ZERO,
            vec![NumberKeyEvent {
                event_index: 0,
                key,
                pressed,
                repeat,
                modifiers,
            }],
        )?;
        self.settle()?;
        Ok(open)
    }
    fn click_at(&mut self, pos: egui::Pos2) -> Result<bool> {
        self.click_button_at(pos, egui::PointerButton::Primary)
    }
    fn click_button_at(&mut self, pos: egui::Pos2, button: egui::PointerButton) -> Result<bool> {
        self.frame(vec![egui::Event::PointerMoved(pos)], Duration::ZERO)?;
        self.frame(
            vec![egui::Event::PointerButton {
                pos,
                button,
                pressed: true,
                modifiers: self.input.modifiers(),
            }],
            Duration::ZERO,
        )?;
        let open = self.frame(
            vec![egui::Event::PointerButton {
                pos,
                button,
                pressed: false,
                modifiers: self.input.modifiers(),
            }],
            Duration::ZERO,
        )?;
        self.settle()?;
        Ok(open)
    }
    pub fn drag(&mut self, control: Control, delta: egui::Vec2) -> Result<()> {
        let start = self.target(control)?;
        self.drag_at(start, delta)
    }
    fn drag_at(&mut self, start: egui::Pos2, delta: egui::Vec2) -> Result<()> {
        self.frame(vec![egui::Event::PointerMoved(start)], Duration::ZERO)?;
        self.frame(
            vec![pointer_with_modifiers(start, true, self.input.modifiers())],
            Duration::ZERO,
        )?;
        self.frame(
            vec![egui::Event::PointerMoved(start + delta * 0.5)],
            Duration::ZERO,
        )?;
        self.frame(
            vec![egui::Event::PointerMoved(start + delta)],
            Duration::ZERO,
        )?;
        self.frame(
            vec![pointer_with_modifiers(
                start + delta,
                false,
                self.input.modifiers(),
            )],
            Duration::ZERO,
        )?;
        self.settle()
    }
    pub fn capture_image(&mut self, name: &str) -> Result<()> {
        self.capture_image_with_inputs(name, false)
    }
    pub fn capture_tutorial(&mut self, name: &str) -> Result<()> {
        self.capture_image_with_inputs(name, true)
    }
    fn capture_image_with_inputs(&mut self, name: &str, show_inputs: bool) -> Result<()> {
        if self.recorder.is_some() {
            return Err("Finish the active clip before capturing a still image".into());
        }
        if self.state.camera.is_transitioning() {
            return Err(format!(
                "Capture {name} requires a settled camera; advance the scenario clock first"
            ));
        }
        let path = format!("assets/{name}.webp");
        validate_path(&path)?;
        let previous = self.show_inputs;
        self.show_inputs = show_inputs;
        let result = (|| {
            // Neither tutorial capture nor layout settling advances time or
            // releases input. A held press remains a held press in the image.
            self.settle()?;
            insert(&mut self.images, path.clone(), self.capture.framed_webp()?)?;
            self.image_inputs.insert(
                path,
                if show_inputs {
                    format!(
                        "tutorial @ {:.3}s: {}",
                        self.time,
                        self.input.summary(self.cursor)
                    )
                } else {
                    "clean".into()
                },
            );
            Ok(())
        })();
        self.show_inputs = previous;
        result
    }
    pub fn require(&mut self, condition: bool, fact: &str) -> Result<()> {
        if !condition {
            return Err(format!("Scenario assertion failed: {fact}"));
        }
        self.facts.push(fact.to_owned());
        Ok(())
    }
    pub fn value(&mut self, key: &str, value: impl ToString) {
        self.values.insert(key.to_owned(), value.to_string());
    }
}

fn pointer(pos: egui::Pos2, pressed: bool) -> egui::Event {
    pointer_with_modifiers(pos, pressed, egui::Modifiers::NONE)
}
fn pointer_with_modifiers(
    pos: egui::Pos2,
    pressed: bool,
    modifiers: egui::Modifiers,
) -> egui::Event {
    egui::Event::PointerButton {
        pos,
        button: egui::PointerButton::Primary,
        pressed,
        modifiers,
    }
}
fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[cfg(test)]
#[path = "tests/harness.rs"]
mod tests;

#[cfg(test)]
#[path = "tests/navigation_return_tests.rs"]
mod navigation_return_tests;
